config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'

  resources :home
  resources :week_data
  resources :day_kondates
  resources :kondates
end

app/controllers/week_data_controller.rb
class WeekDataController < ApplicationController
  before_action :set_week_data, only: %i[show]

  def show
  end

  private

  def set_week_data
    @week_datum = WeekDatum.find(params[:id])
  end
end

app/helpers/week_data_helper.rb
module WeekDataHelper
end

app/views/week_data/show.html.erb
<h2 class="ml-5 pt-3"><%= @week_datum.week %>の週(<%= current_user.nutrition_type.name %>型)</h2>

<div class="d-flex justify-content-center mt-5">
  <table class="table w-75">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">レシピ一覧</th>
        <th scope="col">kcal</th>
        <th scope="col">炭水化物</th>
        <th scope="col">タンパク質</th>
        <th scope="col">脂質</th>
      </tr>
    </thead>

    <% @week_datum.day_data.each do |day_datum| %>
      <tbody>
        <tr class="table-primary">
          <th><%= day_datum.date %></th>
          <td colspan="5">
        </tr>
        <% day_datum.day_kondates.order(:period).each do |day_kondate| %>
          <tr>
            <th scope="row"><%= day_kondate.period_i18n %></th>
            <% if day_kondate.kondate %>
              <td>
                <ul>
                  <% day_kondate.kondate.recipes.each do |recipe| %>
                    <li>
                      <%= recipe.name %>
                    </li>
                  <% end %>
                </ul>
              </td>
              <td><%= day_kondate.kondate.calculate_total(:kcal) %> kcal</td>
              <td><%= day_kondate.kondate.calculate_total(:carbohydrate) %> g</td>
              <td><%= day_kondate.kondate.calculate_total(:protein) %> g</td>
              <td><%= day_kondate.kondate.calculate_total(:fat) %> g</td>
            <% else %>
              <td colspan="4" class="text-muted text-center">未登録</td>
              <td><%= link_to "登録", edit_day_kondate_path(day_kondate), class: "btn btn-outline-success" %></td>
            <% end %>
          </tr>
        <% end %>
        <tr>
          <th colspan="2" scope="row">合計</th>
          <td class="table-<%= compare_to_standard(day_datum.calculate_total(:kcal), current_user.nutrition_type.kcal) %>"><%= day_datum.calculate_total(:kcal) %> kcal</td>
          <td class="table-<%= compare_to_standard(day_datum.calculate_total(:carbohydrate), current_user.nutrition_type.carbohydrate) %>"><%= day_datum.calculate_total(:carbohydrate) %> g</td>
          <td class="table-<%= compare_to_standard(day_datum.calculate_total(:protein), current_user.nutrition_type.protein) %>"><%= day_datum.calculate_total(:protein) %> g</td>
          <td class="table-<%= compare_to_standard(day_datum.calculate_total(:fat), current_user.nutrition_type.fat) %>"><%= day_datum.calculate_total(:fat) %> g</td>
        </tr>
      </tbody>
    <% end %>

    <tbody>
      <tr class="table-info">
        <th colspan="2" scope="row">週の合計</th>
        <td><%= @week_datum.calculate_total(:kcal) %> kcal</td>
        <td><%= @week_datum.calculate_total(:carbohydrate) %> g</td>
        <td><%= @week_datum.calculate_total(:protein) %> g</td>
        <td><%= @week_datum.calculate_total(:fat) %> g</td>
      </tr>
    </tbody>
  </table>
</div>