config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'

  resources :home
  resources :week_data
  resources :day_kondates
  resources :kondates
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def new
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= link_to "新規登録", new_home_path, class: "btn btn-primary" %>
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">タンパク質</th>
      <th scope="col">炭水化物</th>
      <th scope="col">食物繊維</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th>9/21</th>
    </tr>
    <tr>
      <th scope="row">朝食</th>
      <td>10 g</td>
      <td>20 g</td>
      <td>30 g</td>
    </tr>
    <tr>
      <th scope="row">昼食</th>
      <td>20 g</td>
      <td>30 g</td>
      <td>40 g</td>
    </tr>
    <tr>
      <th scope="row">晩ご飯</th>
      <td>40 g</td>
      <td>30 g</td>
      <td>10 g</td>
    </tr>
    <tr>
      <th scope="row">合計</th>
      <td>70 g</td>
      <td>80 g</td>
      <td>80 g</td>
    </tr>
  </tbody>

  <tbody>
    <tr>
      <th>9/22</th>
    </tr>
    <tr>
      <th scope="row">朝食</th>
      <td>10 g</td>
      <td>20 g</td>
      <td>30 g</td>
    </tr>
    <tr>
      <th scope="row">昼食</th>
      <td>20 g</td>
      <td>30 g</td>
      <td>40 g</td>
    </tr>
    <tr>
      <th scope="row">晩ご飯</th>
      <td>40 g</td>
      <td>30 g</td>
      <td>10 g</td>
    </tr>
    <tr>
      <th scope="row">合計</th>
      <td>70 g</td>
      <td>80 g</td>
      <td>80 g</td>
    </tr>
  </tbody>

  <tbody>
    <tr>
      <th>9/23</th>
    </tr>
    <tr>
      <th scope="row">朝食</th>
      <td>10 g</td>
      <td>20 g</td>
      <td>30 g</td>
    </tr>
    <tr>
      <th scope="row">昼食</th>
      <td>20 g</td>
      <td>30 g</td>
      <td>40 g</td>
    </tr>
    <tr>
      <th scope="row">晩ご飯</th>
      <td>40 g</td>
      <td>30 g</td>
      <td>10 g</td>
    </tr>
    <tr>
      <th scope="row">合計</th>
      <td>70 g</td>
      <td>80 g</td>
      <td>80 g</td>
    </tr>
  </tbody>

  <tbody>
    <tr>
      <th scope="row">週の合計</th>
      <td>210 g</td>
      <td>240 g</td>
      <td>240 g</td>
    </tr>
  </tbody>
</table>

app/views/home/new.html.erb
<div>9/21 の朝食</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">タンパク質</th>
      <th scope="col">炭水化物</th>
      <th scope="col">食物繊維</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">目玉焼き</th>
      <td>10 g</td>
      <td>20 g</td>
      <td>30 g</td>
    </tr>
    <tr>
      <th scope="row">トースト</th>
      <td>20 g</td>
      <td>30 g</td>
      <td>40 g</td>
    </tr>
    <tr>
      <th scope="row">コーンスープ</th>
      <td>40 g</td>
      <td>30 g</td>
      <td>10 g</td>
    </tr>
    <tr>
      <th scope="row">合計</th>
      <td>70 g</td>
      <td>80 g</td>
      <td>80 g</td>
    </tr>
  </tbody>
</table>

<%= link_to "追加", new_home_path, class: "btn btn-primary" %>